ALTER TABLE PLANTOPOLIS_USER.LOTEPRODUCCION DROP CONSTRAINT CK_LOTE_ESTADO;
ALTER TABLE PLANTOPOLIS_USER.LOTEPRODUCCION ADD CONSTRAINT CK_LOTE_ESTADO CHECK (ESTADO_LOTE IN ('GERMINANDO', 'CRECIENDO', 'LISTO_PARA_VENTA', 'DESCARTADO', 'EN_TIENDA'));
ALTER TABLE PLANTOPOLIS_USER.HISTORIALESTADOLOTE DROP CONSTRAINT CK_HIST_ESTADO_NUEVO;
ALTER TABLE PLANTOPOLIS_USER.HISTORIALESTADOLOTE ADD CONSTRAINT CK_HIST_ESTADO_NUEVO CHECK (ESTADO_NUEVO IN ('GERMINANDO', 'CRECIENDO', 'LISTO_PARA_VENTA', 'DESCARTADO', 'EN_TIENDA'));
ALTER TABLE PLANTOPOLIS_USER.HISTORIALESTADOLOTE DROP CONSTRAINT CK_HIST_ESTADO_ANT;
ALTER TABLE PLANTOPOLIS_USER.HISTORIALESTADOLOTE ADD CONSTRAINT CK_HIST_ESTADO_ANT CHECK (ESTADO_ANTERIOR IN ('NINGUNO', 'GERMINANDO', 'CRECIENDO', 'LISTO_PARA_VENTA', 'DESCARTADO', 'EN_TIENDA'));
COMMIT;
EXIT;
