package com.plantopolis.backend.application.service;

import com.plantopolis.backend.domain.model.SentenciaRestauracion;
import org.junit.jupiter.api.Test;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ScriptBackupParserTest {

    @Test
    void parsear_FirmaInvalida_LanzaExcepcion() {
        String script = "-- FIRMA INCORRECTA\nINSERT INTO \"ROL\" (\"ID_ROL\") VALUES (1);";
        assertThrows(IllegalArgumentException.class, () -> 
            ScriptBackupParser.parsear(script.getBytes(StandardCharsets.UTF_8)));
    }

    @Test
    void parsear_SentenciaNoPermitida_LanzaExcepcion() {
        String script = "-- PLANTOPOLIS-BACKUP v1\nDROP TABLE \"ROL\";";
        assertThrows(IllegalArgumentException.class, () -> 
            ScriptBackupParser.parsear(script.getBytes(StandardCharsets.UTF_8)));
    }

    @Test
    void parsear_ScriptValido_RetornaSentenciasYReporte() {
        String script = "-- PLANTOPOLIS-BACKUP v1\n" +
                        "-- @reporte ROL=1\n" +
                        "SET DEFINE OFF;\n" +
                        "DELETE FROM \"ROL\";\n" +
                        "INSERT INTO \"ROL\" (\"ID_ROL\") VALUES (1);\n" +
                        "ALTER TABLE \"ROL\" MODIFY (\"ID_ROL\" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));\n" +
                        "COMMIT;";
        
        ScriptBackupParser.ScriptParseado res = ScriptBackupParser.parsear(script.getBytes(StandardCharsets.UTF_8));
        
        assertEquals(1, res.getReporteDeclarado().get("ROL"));
        List<SentenciaRestauracion> sents = res.getSentencias();
        assertEquals(2, sents.size());
        assertEquals("INSERT INTO \"ROL\" (\"ID_ROL\") VALUES (1)", sents.get(0).getSql());
        assertEquals("ALTER TABLE \"ROL\" MODIFY (\"ID_ROL\" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))", sents.get(1).getSql());
    }
}
