-- ==============================================================================
-- PLANTOPOLIS 2.0 - ESQUEMA DE BASE DE DATOS COMPLETO (ORACLE DATABASE 21c XE)
-- Compatible con: Historias de Usuario HU1-HU26 y Requerimientos RF-01 a RF-61
-- Arquitectura: Hexagonal (Ports & Adapters)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. LIMPIEZA DE TABLAS PREVIAS (DROP ORDENADO INVERSO A DEPENDENCIAS)
-- ------------------------------------------------------------------------------
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'COMENTARIOTAREA', 'HISTORIALTAREA', 'TAREA', 'TAREARECURRENTE',
        'MERMA', 'CAUSAMERMA', 'HISTORIALESTADOLOTE', 'LOTEPRODUCCION',
        'ZONA', 'PROVEEDOR', 'PAGO', 'ESTADOPAGO', 'METODOPAGO',
        'DETALLEPEDIDO', 'PEDIDO', 'ESTADOPEDIDO', 'CARRITOITEM',
        'CARRITO', 'ESTADOCARRITO', 'PRODUCTO', 'TIPOPRODUCTO',
        'CATEGORIA', 'USUARIO', 'ROL'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ==============================================================================
-- 1. MÓDULO DE USUARIOS Y AUTENTICACIÓN (RBAC & SEGURIDAD)
-- ==============================================================================

CREATE TABLE Rol (
    id_rol     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_rol_nombre UNIQUE (nombre_rol)
);

CREATE TABLE Usuario (
    id_usuario          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol              NUMBER        NOT NULL,
    nombre_completo     VARCHAR2(150) NOT NULL,
    correo              VARCHAR2(150) NOT NULL,
    contrasena_hash     VARCHAR2(255) NOT NULL,
    telefono            VARCHAR2(20),
    direccion           VARCHAR2(255),
    activo              NUMBER(1)     DEFAULT 1 NOT NULL, -- 1=Activo, 0=Inactivo (HU11b/RF-15/RF-16)
    fecha_registro      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT ck_usuario_activo CHECK (activo IN (0, 1)),
    CONSTRAINT fk_usuario_rol    FOREIGN KEY (id_rol) REFERENCES Rol(id_rol)
);

-- ==============================================================================
-- 2. MÓDULO DE INFRAESTRUCTURA (ZONAS / INVERNADEROS)
-- ==============================================================================

CREATE TABLE Zona (
    id_zona             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(100) NOT NULL,
    capacidad_maxima    NUMBER        NOT NULL,
    tipo_condicion      VARCHAR2(50)  NOT NULL, -- INTERIOR, EXTERIOR
    exposicion_solar    VARCHAR2(50)  NOT NULL, -- SOMBRA, SOL, SEMISOMBRA
    activo              NUMBER(1)     DEFAULT 1 NOT NULL,
    fecha_creacion      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_zona_nombre UNIQUE (nombre),
    CONSTRAINT ck_zona_capacidad CHECK (capacidad_maxima > 0),
    CONSTRAINT ck_zona_activo CHECK (activo IN (0, 1))
);

-- ==============================================================================
-- 3. MÓDULO DE PROVEEDORES
-- ==============================================================================

CREATE TABLE Proveedor (
    id_proveedor        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    contacto            VARCHAR2(100),
    telefono            VARCHAR2(20),
    correo              VARCHAR2(150),
    tipo_insumo         VARCHAR2(100) NOT NULL, -- SEMILLAS, SUSTRATOS, MACETAS, OTROS
    activo              NUMBER(1)     DEFAULT 1 NOT NULL,
    fecha_creacion      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_proveedor_activo CHECK (activo IN (0, 1))
);

-- ==============================================================================
-- 4. MÓDULO DE CATÁLOGO Y PRODUCTOS (E-COMMERCE)
-- ==============================================================================

CREATE TABLE Categoria (
    id_categoria     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(100) NOT NULL,
    descripcion      CLOB,
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre_categoria)
);

CREATE TABLE TipoProducto (
    id_tipo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo  VARCHAR2(80) NOT NULL,
    CONSTRAINT uq_tipoproducto_nombre UNIQUE (nombre_tipo)
);

CREATE TABLE Producto (
    id_producto          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria         NUMBER         NOT NULL,
    id_tipo              NUMBER         NOT NULL,
    nombre_producto      VARCHAR2(150)  NOT NULL,
    descripcion          CLOB,
    precio               NUMBER(10,2)   NOT NULL,
    porcentaje_iva       NUMBER(5,2)    DEFAULT 19.00 NOT NULL, -- IVA/Impuestos aplicables (HU4/RF-08)
    stock                NUMBER         DEFAULT 0 NOT NULL,
    stock_minimo_alerta  NUMBER         DEFAULT 5 NOT NULL, -- Alerta stock crítico (HU8)
    imagen_url           VARCHAR2(300),
    cuidados             CLOB,          -- Consejos de cuidado (HU4/RF-05)
    luz                  VARCHAR2(100),
    riego                VARCHAR2(100),
    tamanio_estimado     VARCHAR2(100),
    activo               NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT ck_producto_precio CHECK (precio >= 0),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0),
    CONSTRAINT ck_producto_activo CHECK (activo IN (0, 1)),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria),
    CONSTRAINT fk_producto_tipo      FOREIGN KEY (id_tipo)      REFERENCES TipoProducto(id_tipo)
);

-- ==============================================================================
-- 5. MÓDULO DE PRODUCCIÓN Y TRAZABILIDAD DE LOTES
-- ==============================================================================

CREATE TABLE LoteProduccion (
    id_lote             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_lote         VARCHAR2(50)  NOT NULL,
    especie             VARCHAR2(100) NOT NULL,
    cantidad_inicial    NUMBER        NOT NULL,
    cantidad_actual     NUMBER        NOT NULL,
    fecha_siembra       DATE          NOT NULL,
    estado_lote         VARCHAR2(40)  DEFAULT 'GERMINANDO' NOT NULL, -- GERMINANDO, CRECIENDO, LISTO_PARA_VENTA, DESCARTADO
    id_zona             NUMBER        NOT NULL,
    id_proveedor        NUMBER,       -- Opcional (HU26/RF-60)
    id_producto         NUMBER,       -- Asociado al vincular con catálogo (HU16/RF-25)
    es_vinculado        NUMBER(1)     DEFAULT 0 NOT NULL, -- Flag anti-duplicidad de stock (RF-26)
    fecha_vinculacion   TIMESTAMP,
    fecha_creacion      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_lote_codigo UNIQUE (codigo_lote),
    CONSTRAINT ck_lote_cant_ini CHECK (cantidad_inicial > 0),
    CONSTRAINT ck_lote_cant_act CHECK (cantidad_actual >= 0),
    CONSTRAINT ck_lote_estado CHECK (estado_lote IN ('GERMINANDO', 'CRECIENDO', 'LISTO_PARA_VENTA', 'DESCARTADO')),
    CONSTRAINT ck_lote_vinculado CHECK (es_vinculado IN (0, 1)),
    CONSTRAINT fk_lote_zona      FOREIGN KEY (id_zona)      REFERENCES Zona(id_zona),
    CONSTRAINT fk_lote_proveedor FOREIGN KEY (id_proveedor) REFERENCES Proveedor(id_proveedor),
    CONSTRAINT fk_lote_producto  FOREIGN KEY (id_producto)  REFERENCES Producto(id_producto)
);

CREATE TABLE HistorialEstadoLote (
    id_historial_lote   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote             NUMBER        NOT NULL,
    id_usuario          NUMBER        NOT NULL, -- Auditor / Trabajador que realizó el cambio (RF-23)
    estado_anterior     VARCHAR2(40)  NOT NULL,
    estado_nuevo        VARCHAR2(40)  NOT NULL,
    observaciones       CLOB,
    fecha_cambio        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_hlt_lote    FOREIGN KEY (id_lote)    REFERENCES LoteProduccion(id_lote),
    CONSTRAINT fk_hlt_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
);

-- ==============================================================================
-- 6. MÓDULO DE SALUD Y MERMAS
-- ==============================================================================

CREATE TABLE CausaMerma (
    id_causa            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_causa        VARCHAR2(80) NOT NULL, -- PLAGA, ENFERMEDAD, CLIMA, MANIPULACION, OTRO (HU23)
    activo              NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT uq_causa_nombre UNIQUE (nombre_causa),
    CONSTRAINT ck_causamerma_activo CHECK (activo IN (0, 1))
);

CREATE TABLE Merma (
    id_merma            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote             NUMBER       NOT NULL,
    id_causa            NUMBER       NOT NULL, -- Catálogo predefinido (HU23/RF-56)
    id_usuario          NUMBER       NOT NULL, -- Trabajador que reporta la pérdida
    cantidad_perdida    NUMBER       NOT NULL,
    fecha_merma         DATE         NOT NULL,
    observaciones       CLOB,
    fecha_registro      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_merma_cantidad CHECK (cantidad_perdida > 0),
    CONSTRAINT fk_merma_lote    FOREIGN KEY (id_lote)    REFERENCES LoteProduccion(id_lote),
    CONSTRAINT fk_merma_causa   FOREIGN KEY (id_causa)   REFERENCES CausaMerma(id_causa),
    CONSTRAINT fk_merma_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
);

-- ==============================================================================
-- 7. MÓDULO OPERATIVO (TAREAS KANBAN & CALENDARIO DE CUIDADOS)
-- ==============================================================================

CREATE TABLE TareaRecurrente (
    id_tarea_recurrente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_tarea              VARCHAR2(50) NOT NULL, -- RIEGO, PODA, FERTILIZACION, FUMIGACION, OTRO
    prioridad               VARCHAR2(20) DEFAULT 'MEDIA' NOT NULL, -- ALTA, MEDIA, BAJA
    frecuencia_dias         NUMBER       NOT NULL, -- Ciclo en días (RF-31)
    id_zona                 NUMBER,      -- XOR con id_lote
    id_lote                 NUMBER,      -- XOR con id_zona
    id_trabajador_asignado  NUMBER,      -- Opcional (Backlog)
    activo                  NUMBER(1)    DEFAULT 1 NOT NULL,
    fecha_proxima_ejecucion DATE         NOT NULL,
    fecha_creacion          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_tr_frecuencia CHECK (frecuencia_dias > 0),
    CONSTRAINT ck_tr_prioridad  CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT ck_tr_activo     CHECK (activo IN (0, 1)),
    -- Regla de Negocio HU17 / RF-28: Asociada a lote O zona (Exclusión mutua XOR)
    CONSTRAINT ck_tr_objetivo_xor CHECK (
        (id_zona IS NOT NULL AND id_lote IS NULL) OR 
        (id_zona IS NULL AND id_lote IS NOT NULL)
    ),
    CONSTRAINT fk_tr_zona       FOREIGN KEY (id_zona)                REFERENCES Zona(id_zona),
    CONSTRAINT fk_tr_lote       FOREIGN KEY (id_lote)                REFERENCES LoteProduccion(id_lote),
    CONSTRAINT fk_tr_trabajador FOREIGN KEY (id_trabajador_asignado) REFERENCES Usuario(id_usuario)
);

CREATE TABLE Tarea (
    id_tarea                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tarea_recurrente     NUMBER,      -- Opcional (si proviene de job automático RF-32)
    tipo_tarea              VARCHAR2(50) NOT NULL,
    prioridad               VARCHAR2(20) DEFAULT 'MEDIA' NOT NULL,
    estado_tarea            VARCHAR2(40) DEFAULT 'POR_HACER' NOT NULL, -- POR_HACER, EN_PROGRESO, EN_REVISION, COMPLETADA, BLOQUEADA
    id_zona                 NUMBER,
    id_lote                 NUMBER,
    id_trabajador_asignado  NUMBER,      -- Opcional para backlog (RF-30)
    fecha_limite            DATE         NOT NULL,
    alerta_vencida_enviada  NUMBER(1)    DEFAULT 0 NOT NULL, -- Control de Idempotencia de emails (RF-44)
    fecha_creacion          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_completada        TIMESTAMP,
    CONSTRAINT ck_ta_prioridad CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT ck_ta_estado    CHECK (estado_tarea IN ('POR_HACER', 'EN_PROGRESO', 'EN_REVISION', 'COMPLETADA', 'BLOQUEADA')),
    CONSTRAINT ck_ta_alerta    CHECK (alerta_vencida_enviada IN (0, 1)),
    -- Regla XOR: Asociada a Lote o Zona
    CONSTRAINT ck_ta_objetivo_xor CHECK (
        (id_zona IS NOT NULL AND id_lote IS NULL) OR 
        (id_zona IS NULL AND id_lote IS NOT NULL)
    ),
    CONSTRAINT fk_ta_recurrente FOREIGN KEY (id_tarea_recurrente)    REFERENCES TareaRecurrente(id_tarea_recurrente),
    CONSTRAINT fk_ta_zona       FOREIGN KEY (id_zona)                REFERENCES Zona(id_zona),
    CONSTRAINT fk_ta_lote       FOREIGN KEY (id_lote)                REFERENCES LoteProduccion(id_lote),
    CONSTRAINT fk_ta_trabajador FOREIGN KEY (id_trabajador_asignado) REFERENCES Usuario(id_usuario)
);

CREATE TABLE HistorialTarea (
    id_historial_tarea      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tarea                NUMBER       NOT NULL,
    id_usuario              NUMBER       NOT NULL, -- Quién realizó el cambio o reasignación
    tipo_cambio             VARCHAR2(30) NOT NULL, -- ESTADO, REASIGNACION (RF-47)
    estado_anterior         VARCHAR2(40),
    estado_nuevo            VARCHAR2(40),
    id_trabajador_anterior  NUMBER,
    id_trabajador_nuevo     NUMBER,
    fecha_cambio            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_ht_tipo CHECK (tipo_cambio IN ('ESTADO', 'REASIGNACION', 'CREACION')),
    CONSTRAINT fk_ht_tarea   FOREIGN KEY (id_tarea)               REFERENCES Tarea(id_tarea),
    CONSTRAINT fk_ht_usuario FOREIGN KEY (id_usuario)             REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_ht_trab_ant FOREIGN KEY (id_trabajador_anterior) REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_ht_trab_nue FOREIGN KEY (id_trabajador_nuevo)    REFERENCES Usuario(id_usuario)
);

CREATE TABLE ComentarioTarea (
    id_comentario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tarea            NUMBER    NOT NULL,
    id_usuario          NUMBER    NOT NULL, -- Autor del comentario (RF-40)
    comentario          CLOB      NOT NULL,
    fecha_creacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cta_tarea   FOREIGN KEY (id_tarea)   REFERENCES Tarea(id_tarea),
    CONSTRAINT fk_cta_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
);

-- ==============================================================================
-- 8. MÓDULO DE CARRITO Y PEDIDOS (E-COMMERCE TRANSACCIONAL)
-- ==============================================================================

CREATE TABLE EstadoCarrito (
    id_estado_carrito  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion        VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_estado_carrito UNIQUE (descripcion)
);

CREATE TABLE Carrito (
    id_carrito          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          NUMBER    NOT NULL,
    id_estado_carrito   NUMBER    NOT NULL,
    fecha_creacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_carrito_usuario FOREIGN KEY (id_usuario)        REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_carrito_estado  FOREIGN KEY (id_estado_carrito) REFERENCES EstadoCarrito(id_estado_carrito)
);

CREATE TABLE CarritoItem (
    id_item     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito  NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad    NUMBER NOT NULL,
    CONSTRAINT ck_ci_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_item_carrito  FOREIGN KEY (id_carrito)  REFERENCES Carrito(id_carrito),
    CONSTRAINT fk_item_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

CREATE TABLE EstadoPedido (
    id_estado_pedido   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_estado VARCHAR2(80) NOT NULL,
    CONSTRAINT uq_estado_pedido UNIQUE (descripcion_estado)
);

CREATE TABLE Pedido (
    id_pedido        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       NUMBER        NOT NULL,
    id_estado_pedido NUMBER        NOT NULL,
    numero_pedido    VARCHAR2(30)  NOT NULL,
    subtotal         NUMBER(10,2)  NOT NULL,
    impuestos        NUMBER(10,2)  NOT NULL, -- Impuestos discriminados (HU4/HU6)
    total            NUMBER(10,2)  NOT NULL, -- Cálculo total automático (RF-08)
    direccion_envio  VARCHAR2(255) NOT NULL,
    fecha_pedido     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_pedido_numero UNIQUE (numero_pedido),
    CONSTRAINT ck_pedido_total CHECK (total >= 0),
    CONSTRAINT fk_pedido_usuario FOREIGN KEY (id_usuario)       REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_pedido_estado  FOREIGN KEY (id_estado_pedido) REFERENCES EstadoPedido(id_estado_pedido)
);

CREATE TABLE DetallePedido (
    id_detalle      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido       NUMBER       NOT NULL,
    id_producto     NUMBER       NOT NULL,
    cantidad        NUMBER       NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    subtotal        NUMBER(10,2) NOT NULL,
    CONSTRAINT ck_dp_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_dp_pedido   FOREIGN KEY (id_pedido)   REFERENCES Pedido(id_pedido),
    CONSTRAINT fk_dp_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

CREATE TABLE MetodoPago (
    id_metodo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_metodo  VARCHAR2(80) NOT NULL,
    CONSTRAINT uq_metodo_pago UNIQUE (nombre_metodo)
);

CREATE TABLE EstadoPago (
    id_estado_pago          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_estado_pago VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_estado_pago UNIQUE (descripcion_estado_pago)
);

CREATE TABLE Pago (
    id_pago                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido               NUMBER        NOT NULL,
    id_metodo               NUMBER        NOT NULL,
    id_estado_pago          NUMBER        NOT NULL,
    monto                   NUMBER(10,2)  NOT NULL,
    pasarela_transaccion_id VARCHAR2(100),
    factura_pdf_url         VARCHAR2(300), -- Factura descargable en PDF (HU6/HU7)
    fecha_pago              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_pago_pedido UNIQUE (id_pedido),
    CONSTRAINT ck_pago_monto  CHECK (monto >= 0),
    CONSTRAINT fk_pago_pedido FOREIGN KEY (id_pedido)      REFERENCES Pedido(id_pedido),
    CONSTRAINT fk_pago_metodo FOREIGN KEY (id_metodo)      REFERENCES MetodoPago(id_metodo),
    CONSTRAINT fk_pago_estado FOREIGN KEY (id_estado_pago) REFERENCES EstadoPago(id_estado_pago)
);

-- ==============================================================================
-- 9. ÍNDICES ESTRATÉGICOS DE RENDIMIENTO
-- ==============================================================================

CREATE INDEX idx_usuario_rol        ON Usuario(id_rol);
CREATE INDEX idx_lote_zona          ON LoteProduccion(id_zona);
CREATE INDEX idx_lote_estado        ON LoteProduccion(estado_lote);
CREATE INDEX idx_lote_producto      ON LoteProduccion(id_producto);
CREATE INDEX idx_tarea_trabajador   ON Tarea(id_trabajador_asignado);
CREATE INDEX idx_tarea_estado       ON Tarea(estado_tarea);
CREATE INDEX idx_tarea_fecha_limite ON Tarea(fecha_limite);
CREATE INDEX idx_merma_lote         ON Merma(id_lote);
CREATE INDEX idx_merma_fecha        ON Merma(fecha_merma);
CREATE INDEX idx_pedido_usuario     ON Pedido(id_usuario);
CREATE INDEX idx_pedido_fecha       ON Pedido(fecha_pedido);

-- ==============================================================================
-- 10. DATOS MAESTROS INICIALES (CATÁLOGOS Y SEMILLAS DE NEGOCIO)
-- ==============================================================================

-- Roles de usuario (Seguridad RBAC)
INSERT INTO Rol (nombre_rol) VALUES ('ADMINISTRADOR');
INSERT INTO Rol (nombre_rol) VALUES ('TRABAJADOR');
INSERT INTO Rol (nombre_rol) VALUES ('CLIENTE');

-- Estados de pedido
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('PENDIENTE');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('EN_PREPARACION');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('ENVIADO');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('ENTREGADO');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('CANCELADO');

-- Estados de carrito
INSERT INTO EstadoCarrito (descripcion) VALUES ('ACTIVO');
INSERT INTO EstadoCarrito (descripcion) VALUES ('ABANDONADO');
INSERT INTO EstadoCarrito (descripcion) VALUES ('PROCESADO');

-- Métodos de pago
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TARJETA_CREDITO');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TARJETA_DEBITO');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('PSE');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TRANSFERENCIA_BANCARIA');

-- Estados de pago
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('PENDIENTE');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('APROBADO');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('RECHAZADO');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('REEMBOLSADO');

-- Causas de merma oficiales (HU23 / RF-56)
INSERT INTO CausaMerma (nombre_causa) VALUES ('PLAGA');
INSERT INTO CausaMerma (nombre_causa) VALUES ('ENFERMEDAD_HONGO');
INSERT INTO CausaMerma (nombre_causa) VALUES ('CLIMA_EXCESO_CALOR');
INSERT INTO CausaMerma (nombre_causa) VALUES ('CLIMA_EXCESO_AGUA');
INSERT INTO CausaMerma (nombre_causa) VALUES ('ERROR_MANIPULACION');
INSERT INTO CausaMerma (nombre_causa) VALUES ('OTRO');

-- Categorías de catálogo
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Plantas de Interior', 'Especies adaptadas a baja luminosidad y ambientes cerrados');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Plantas de Exterior', 'Plantas resistentes al sol directo y jardines abiertos');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Suculentas y Cactus', 'Plantas de bajo requerimiento hídrico');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Aromáticas y Medicinales', 'Plantas útiles para cocina y fitoterapia');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Insumos y Accesorios', 'Macetas, sustratos y abonos orgánicos');

-- Tipos de producto
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Planta Viva');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Semilla');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Sustrato');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Maceta');

-- Zonas de demostración
INSERT INTO Zona (nombre, capacidad_maxima, tipo_condicion, exposicion_solar) 
VALUES ('Invernadero Principal Alpha', 500, 'INTERIOR', 'SEMISOMBRA');
INSERT INTO Zona (nombre, capacidad_maxima, tipo_condicion, exposicion_solar) 
VALUES ('Patio Exterior Sur', 1200, 'EXTERIOR', 'SOL');
INSERT INTO Zona (nombre, capacidad_maxima, tipo_condicion, exposicion_solar) 
VALUES ('Cámara de Germinación 1', 300, 'INTERIOR', 'SOMBRA');

-- Proveedor inicial
INSERT INTO Proveedor (nombre, contacto, telefono, correo, tipo_insumo)
VALUES ('Semillas Andinas SAS', 'Carlos Gómez', '+57 3001234567', 'contacto@semillasandinas.co', 'SEMILLAS');

COMMIT;
