-- ============================================================
-- 1. ROL
-- ============================================================
CREATE TABLE Rol (
    id_rol   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(50) NOT NULL
);

-- ============================================================
-- 2. USUARIO
-- ============================================================
CREATE TABLE Usuario (
    id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol           NUMBER        NOT NULL,
    nombre_completo  VARCHAR2(150) NOT NULL,
    correo           VARCHAR2(150) NOT NULL,
    contrasena_hash  VARCHAR2(255) NOT NULL,
    telefono         VARCHAR2(20),
    direccion        VARCHAR2(255),
    fecha_registro   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT fk_usuario_rol    FOREIGN KEY (id_rol) REFERENCES Rol(id_rol)
);

-- ============================================================
-- 3. CATEGORIA
-- ============================================================
CREATE TABLE Categoria (
    id_categoria     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(100) NOT NULL,
    descripcion      CLOB
);

-- ============================================================
-- 4. TIPOPRODUCTO
-- ============================================================
CREATE TABLE TipoProducto (
    id_tipo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo  VARCHAR2(80) NOT NULL
);

-- ============================================================
-- 5. PRODUCTO
-- ============================================================
CREATE TABLE Producto (
    id_producto       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria      NUMBER         NOT NULL,
    id_tipo           NUMBER         NOT NULL,
    nombre_producto   VARCHAR2(150)  NOT NULL,
    descripcion       CLOB,
    precio            NUMBER(10,2)   NOT NULL,
    stock             NUMBER         NOT NULL,
    imagen_url        VARCHAR2(300),
    cuidados          CLOB,
    luz               VARCHAR2(100),
    riego             VARCHAR2(100),
    tamanio_estimado  VARCHAR2(100),
    activo            NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria),
    CONSTRAINT fk_producto_tipo      FOREIGN KEY (id_tipo)      REFERENCES TipoProducto(id_tipo)
);

-- ============================================================
-- 6. ESTADOPEDIDO
-- ============================================================
CREATE TABLE EstadoPedido (
    id_estado          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_estado VARCHAR2(80) NOT NULL
);

-- ============================================================
-- 7. ESTADOCARRITO
-- ============================================================
CREATE TABLE EstadoCarrito (
    id_estado_carrito  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion        VARCHAR2(50) NOT NULL
);

-- ============================================================
-- 8. CARRITO
-- ============================================================
CREATE TABLE Carrito (
    id_carrito        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER    NOT NULL,
    id_estado_carrito NUMBER    NOT NULL,
    fecha_creacion    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrito_usuario FOREIGN KEY (id_usuario)        REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_carrito_estado  FOREIGN KEY (id_estado_carrito) REFERENCES EstadoCarrito(id_estado_carrito)
);

-- ============================================================
-- 9. CARRITOITEM
-- ============================================================
CREATE TABLE CarritoItem (
    id_item     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito  NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad    NUMBER NOT NULL,
    CONSTRAINT fk_item_carrito  FOREIGN KEY (id_carrito)  REFERENCES Carrito(id_carrito),
    CONSTRAINT fk_item_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

-- ============================================================
-- 10. PEDIDO
-- ============================================================
CREATE TABLE Pedido (
    id_pedido        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       NUMBER        NOT NULL,
    id_estado        NUMBER        NOT NULL,
    id_carrito       NUMBER,
    fecha_pedido     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    direccion_envio  VARCHAR2(255),
    numero_pedido    VARCHAR2(20)  NOT NULL,
    CONSTRAINT uq_pedido_numero  UNIQUE (numero_pedido),
    CONSTRAINT fk_pedido_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_pedido_estado  FOREIGN KEY (id_estado)  REFERENCES EstadoPedido(id_estado),
    CONSTRAINT fk_pedido_carrito FOREIGN KEY (id_carrito) REFERENCES Carrito(id_carrito)
);

-- ============================================================
-- 11. DETALLEPEDIDO
-- ============================================================
CREATE TABLE DetallePedido (
    id_detalle      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido       NUMBER       NOT NULL,
    id_producto     NUMBER       NOT NULL,
    cantidad        NUMBER       NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detalle_pedido   FOREIGN KEY (id_pedido)   REFERENCES Pedido(id_pedido),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto)
);

-- ============================================================
-- 12. METODOPAGO
-- ============================================================
CREATE TABLE MetodoPago (
    id_metodo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_metodo  VARCHAR2(80) NOT NULL
);

-- ============================================================
-- 13. ESTADOPAGO
-- ============================================================
CREATE TABLE EstadoPago (
    id_estado_pago          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_estado_pago VARCHAR2(50) NOT NULL
);

-- ============================================================
-- 14. PAGO
-- ============================================================
CREATE TABLE Pago (
    id_pago        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido      NUMBER       NOT NULL,
    id_metodo      NUMBER       NOT NULL,
    id_estado_pago NUMBER       NOT NULL,
    monto          NUMBER(10,2) NOT NULL,
    fecha_pago     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pago_pedido    UNIQUE (id_pedido),
    CONSTRAINT fk_pago_pedido    FOREIGN KEY (id_pedido)      REFERENCES Pedido(id_pedido),
    CONSTRAINT fk_pago_metodo    FOREIGN KEY (id_metodo)      REFERENCES MetodoPago(id_metodo),
    CONSTRAINT fk_pago_estado    FOREIGN KEY (id_estado_pago) REFERENCES EstadoPago(id_estado_pago)
);

-- ============================================================
-- DATOS INICIALES (Catálogos)
-- ============================================================

-- Roles
INSERT INTO Rol (nombre) VALUES ('CLIENTE');
INSERT INTO Rol (nombre) VALUES ('ADMINISTRADOR');

-- Estados de pedido
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('PENDIENTE');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('PREPARANDO');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('ENVIADO');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('ENTREGADO');
INSERT INTO EstadoPedido (descripcion_estado) VALUES ('CANCELADO');

-- Estados de carrito
INSERT INTO EstadoCarrito (descripcion) VALUES ('ACTIVO');
INSERT INTO EstadoCarrito (descripcion) VALUES ('CONVERTIDO');
INSERT INTO EstadoCarrito (descripcion) VALUES ('ABANDONADO');

-- Métodos de pago
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TARJETA_CREDITO');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TARJETA_DEBITO');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('TRANSFERENCIA');
INSERT INTO MetodoPago (nombre_metodo) VALUES ('EFECTIVO');

-- Estados de pago
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('PENDIENTE');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('APROBADO');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('RECHAZADO');
INSERT INTO EstadoPago (descripcion_estado_pago) VALUES ('REEMBOLSADO');

-- Categorías de productos
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Plantas de Interior', 'Plantas ideales para espacios cerrados con poca luz');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Plantas de Exterior', 'Plantas para jardines y espacios abiertos');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Suculentas y Cactus', 'Plantas de bajo mantenimiento y poca agua');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Plantas Aromáticas', 'Hierbas y plantas con fragancia');
INSERT INTO Categoria (nombre_categoria, descripcion) VALUES ('Accesorios', 'Macetas, herramientas y sustratos');

-- Tipos de producto
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Planta');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Semilla');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Accesorio');
INSERT INTO TipoProducto (nombre_tipo) VALUES ('Sustrato');


